services:
  postgres:
    image: postgres:15
    container_name: nfc-scavenger-hunt-db
    environment:
      POSTGRES_DB: nfc_scavenger_hunt
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    restart: unless-stopped

volumes:
  postgres_data:
